window.__BITTIBOL_LEXICON = [
  // ==================== BODY & BEAUTY ====================
  { pahari: 'dandru', gloss_en: 'teeth (diminutive -ru)', avoid: ['daant'], tags: ['body'], notes: 'Chitte dandru = white teeth, a beauty trope' },
  { pahari: 'akhyun', gloss_en: 'eyes (plural)', avoid: ['aankhen'], tags: ['body'] },
  { pahari: 'nain', gloss_en: 'eyes (poetic)', avoid: [], tags: ['body'], notes: 'Used in romantic/poetic contexts' },
  { pahari: 'mukharu', gloss_en: 'face (diminutive)', avoid: ['chehra', 'muh'], tags: ['body'] },
  { pahari: 'gallu', gloss_en: 'cheek (diminutive)', avoid: ['gaal'], tags: ['body'] },
  { pahari: 'naak', gloss_en: 'nose', avoid: [], tags: ['body'] },
  { pahari: 'kaan', gloss_en: 'ear', avoid: [], tags: ['body'] },
  { pahari: 'haath', gloss_en: 'hand', avoid: [], tags: ['body'] },
  { pahari: 'pair', gloss_en: 'foot / feet', avoid: ['paon', 'per'], tags: ['body'] },
  { pahari: 'baal', gloss_en: 'hair', avoid: [], tags: ['body'] },
  { pahari: 'sheeshu', gloss_en: 'head', avoid: ['sir'], tags: ['body'] },
  { pahari: 'goru', gloss_en: 'fair / light-skinned (diminutive)', avoid: ['gora'], tags: ['beauty'], notes: 'Fair complexion trope in folk songs' },
  { pahari: 'kaalu', gloss_en: 'dark / dusky (diminutive)', avoid: ['kala'], tags: ['beauty'] },

  // ==================== PEOPLE & KINSHIP ====================
  { pahari: 'bitti', gloss_en: 'girl / daughter', avoid: ['larki', 'beti'], tags: ['people'] },
  { pahari: 'bittu', gloss_en: 'boy / son', avoid: ['larka', 'beta'], tags: ['people'] },
  { pahari: 'baabu', gloss_en: 'father', avoid: ['pita', 'papa'], tags: ['kinship'] },
  { pahari: 'aama', gloss_en: 'mother', avoid: ['mata', 'maa'], tags: ['kinship'] },
  { pahari: 'bhailu', gloss_en: 'brother', avoid: ['bhai'], tags: ['kinship'] },
  { pahari: 'bhabhi', gloss_en: 'brother\'s wife', avoid: [], tags: ['kinship'] },
  { pahari: 'baani', gloss_en: 'sister', avoid: ['behen'], tags: ['kinship'] },
  { pahari: 'mausi', gloss_en: 'mother\'s sister', avoid: [], tags: ['kinship'] },
  { pahari: 'chaachu', gloss_en: 'father\'s younger brother', avoid: [], tags: ['kinship'] },
  { pahari: 'taau', gloss_en: 'father\'s elder brother', avoid: [], tags: ['kinship'] },
  { pahari: 'bua', gloss_en: 'father\'s sister', avoid: [], tags: ['kinship'] },
  { pahari: 'dadi', gloss_en: 'paternal grandmother', avoid: [], tags: ['kinship'] },
  { pahari: 'naani', gloss_en: 'maternal grandmother', avoid: [], tags: ['kinship'] },
  { pahari: 'jwaai', gloss_en: 'son-in-law', avoid: [], tags: ['kinship'] },
  { pahari: 'bauri', gloss_en: 'bride / newlywed woman', avoid: ['dulhan'], tags: ['people'] },
  { pahari: 'lendu', gloss_en: 'groom', avoid: ['dulha'], tags: ['people'] },
  { pahari: 'saagi', gloss_en: 'friend (female)', avoid: ['saheli'], tags: ['people'] },
  { pahari: 'yaar', gloss_en: 'friend (male)', avoid: ['dost'], tags: ['people'] },
  { pahari: 'log', gloss_en: 'people / folk', avoid: [], tags: ['people'] },
  { pahari: 'jaat', gloss_en: 'caste / kind / type', avoid: [], tags: ['people'] },

  // ==================== GRAMMAR & FUNCTION WORDS ====================
  { pahari: 'kundu', gloss_en: 'where', avoid: ['kahan'], tags: ['grammar'] },
  { pahari: 'kuthu', gloss_en: 'where (variant)', avoid: ['kidhar'], tags: ['grammar'] },
  { pahari: 'minjo', gloss_en: 'to me', avoid: ['mainu', 'mujhe'], tags: ['grammar'] },
  { pahari: 'tinjo', gloss_en: 'to you (singular)', avoid: ['tenu', 'tujhe'], tags: ['grammar'] },
  { pahari: 'unjo', gloss_en: 'to him/her', avoid: ['ohnu', 'use'], tags: ['grammar'] },
  { pahari: 'aapdu', gloss_en: 'our / our own', avoid: ['apna'], tags: ['grammar'], notes: 'Reflexive possessive, "aapdu graan" = our village' },
  { pahari: 'manjh', gloss_en: 'in / inside', avoid: ['ch', 'vich', 'de naal'], tags: ['grammar'], notes: 'Use "manjh" not "ch" or "vich" for "in"' },
  { pahari: 'ri', gloss_en: 'genitive feminine suffix', avoid: ['di'], tags: ['grammar'], notes: '"ri" not "di" for feminine genitive' },
  { pahari: 'ra', gloss_en: 'genitive masculine suffix', avoid: ['da'], tags: ['grammar'], notes: '"ra" not "da" for masculine genitive' },
  { pahari: 're', gloss_en: 'genitive oblique suffix', avoid: ['de'], tags: ['grammar'], notes: '"re" not "de" for oblique genitive' },
  { pahari: 'jo', gloss_en: 'that / which / who', avoid: ['jo (acceptable)'], tags: ['grammar'] },
  { pahari: 'ni', gloss_en: 'feminine marker / emphasis particle', avoid: [], tags: ['grammar'], notes: 'As in "lai lo ni" — emphatic feminine particle' },
  { pahari: 'ta', gloss_en: 'then / so (connective)', avoid: ['to', 'phir'], tags: ['grammar'] },
  { pahari: 'bhi', gloss_en: 'also / too', avoid: ['vi'], tags: ['grammar'] },
  { pahari: 'hi', gloss_en: 'only / exactly', avoid: [], tags: ['grammar'] },
  { pahari: 'ho', gloss_en: 'vocative / exclamation', avoid: ['o', 'are'], tags: ['grammar'], notes: 'Used before names: "Ho bitti..." = Oh girl...' },
  { pahari: 'ae', gloss_en: 'is (present copula)', avoid: ['hai'], tags: ['grammar'] },
  { pahari: 'thae', gloss_en: 'was (past copula)', avoid: ['tha'], tags: ['grammar'] },
  { pahari: 'cha', gloss_en: 'is (emphatic copula)', avoid: [], tags: ['grammar'], notes: 'Shortened from "chha"' },
  { pahari: 'jaalu', gloss_en: 'when', avoid: ['jadon', 'jab'], tags: ['grammar'] },
  { pahari: 'taalu', gloss_en: 'then (at that time)', avoid: ['tadon', 'tab'], tags: ['grammar'] },
  { pahari: 'kinna', gloss_en: 'how much / how many', avoid: ['kitna'], tags: ['grammar'] },
  { pahari: 'itna', gloss_en: 'this much', avoid: [], tags: ['grammar'] },
  { pahari: 'jyun', gloss_en: 'like / as / similar to', avoid: ['jaise', 'jiven'], tags: ['grammar'] },
  { pahari: 'tyun', gloss_en: 'like that / in that manner', avoid: ['taise', 'tiven'], tags: ['grammar'] },

  // ==================== NATURE & LANDSCAPE ====================
  { pahari: 'ghughuti', gloss_en: 'a bird (songbird / dove)', avoid: ['chidiya'], tags: ['nature'] },
  { pahari: 'banjar', gloss_en: 'barren / fallow land', avoid: [], tags: ['nature'] },
  { pahari: 'bagaich', gloss_en: 'garden', avoid: ['bagh'], tags: ['nature'] },
  { pahari: 'deodar', gloss_en: 'Himalayan cedar tree', avoid: [], tags: ['nature'] },
  { pahari: 'pahad', gloss_en: 'mountain', avoid: ['pahad (acceptable)'], tags: ['nature'] },
  { pahari: 'dhaar', gloss_en: 'mountain ridge / crest', avoid: [], tags: ['nature'] },
  { pahari: 'jangle', gloss_en: 'forest', avoid: ['jungle (acceptable)'], tags: ['nature'] },
  { pahari: 'baanu', gloss_en: 'oak tree', avoid: [], tags: ['nature'] },
  { pahari: 'buransh', gloss_en: 'rhododendron flower', avoid: [], tags: ['nature'], notes: 'State flower, iconic in songs' },
  { pahari: 'khaalu', gloss_en: 'ravine / deep valley', avoid: [], tags: ['nature'] },
  { pahari: 'gadera', gloss_en: 'mountain stream', avoid: ['nadi (small)'], tags: ['nature'] },
  { pahari: 'naun', gloss_en: 'river (large)', avoid: ['nadi'], tags: ['nature'] },
  { pahari: 'chashma', gloss_en: 'spring / water source', avoid: [], tags: ['nature'] },
  { pahari: 'ghaas', gloss_en: 'grass', avoid: [], tags: ['nature'] },
  { pahari: 'phool', gloss_en: 'flower', avoid: [], tags: ['nature'] },
  { pahari: 'kaante', gloss_en: 'thorns', avoid: [], tags: ['nature'] },
  { pahari: 'badal', gloss_en: 'cloud', avoid: [], tags: ['nature'] },
  { pahari: 'barkha', gloss_en: 'rain / monsoon', avoid: ['baarish'], tags: ['nature'] },
  { pahari: 'baraf', gloss_en: 'snow / ice', avoid: [], tags: ['nature'] },
  { pahari: 'dhupp', gloss_en: 'sunshine / sunlight', avoid: ['dhoop'], tags: ['nature'] },
  { pahari: 'chaan', gloss_en: 'shade / shadow', avoid: ['chhaya'], tags: ['nature'] },
  { pahari: 'hawa', gloss_en: 'wind / breeze', avoid: [], tags: ['nature'] },
  { pahari: 'aakash', gloss_en: 'sky', avoid: ['asman'], tags: ['nature'] },
  { pahari: 'taare', gloss_en: 'stars', avoid: ['sitaare'], tags: ['nature'] },
  { pahari: 'chaand', gloss_en: 'moon', avoid: [], tags: ['nature'] },
  { pahari: 'suuraj', gloss_en: 'sun', avoid: ['suraj'], tags: ['nature'] },
  { pahari: 'khet', gloss_en: 'field', avoid: [], tags: ['nature', 'agriculture'] },
  { pahari: 'pashu', gloss_en: 'animal / livestock', avoid: ['janwar'], tags: ['nature', 'agriculture'] },

  // ==================== PLACES (REAL & MYTHICAL) ====================
  { pahari: 'shimle', gloss_en: 'Shimla (oblique case)', avoid: ['shimla'], tags: ['place'] },
  { pahari: 'dharampur', gloss_en: 'a town / village name', avoid: [], tags: ['place'] },
  { pahari: 'kamru', gloss_en: 'a mythological fort / place', avoid: [], tags: ['place'] },
  { pahari: 'graan', gloss_en: 'village', avoid: ['pind', 'gaon'], tags: ['place'] },
  { pahari: 'shahar', gloss_en: 'city / town', avoid: ['sheher'], tags: ['place'] },
  { pahari: 'sadku', gloss_en: 'road / street', avoid: ['sadak'], tags: ['place'], notes: 'Oblique form used: "sadku pe" = on the road' },
  { pahari: 'bazaar', gloss_en: 'market', avoid: [], tags: ['place'] },
  { pahari: 'mandir', gloss_en: 'temple', avoid: [], tags: ['place'] },
  { pahari: 'deotha', gloss_en: 'village deity shrine', avoid: [], tags: ['place', 'culture'] },
  { pahari: 'chauraha', gloss_en: 'crossroads', avoid: [], tags: ['place'] },
  { pahari: 'chopal', gloss_en: 'village gathering ground', avoid: [], tags: ['place', 'culture'] },
  { pahari: 'dera', gloss_en: 'homestead / temporary dwelling', avoid: [], tags: ['place'] },
  { pahari: 'kothi', gloss_en: 'house / mansion', avoid: ['ghar'], tags: ['place'], notes: '"Aaja meri kothi" = come to my house (romantic)' },
  { pahari: 'gaushala', gloss_en: 'cowshed', avoid: [], tags: ['place'] },
  { pahari: 'naule', gloss_en: 'stepwell / water tank', avoid: [], tags: ['place'] },

  // ==================== TIME & SEASONS ====================
  { pahari: 'rouni', gloss_en: 'night', avoid: ['raat'], tags: ['time'] },
  { pahari: 'dihu', gloss_en: 'day', avoid: ['din'], tags: ['time'] },
  { pahari: 'saun', gloss_en: 'monsoon month (Shravan)', avoid: ['sawan'], tags: ['time'] },
  { pahari: 'baishakh', gloss_en: 'harvest month (April-May)', avoid: [], tags: ['time'] },
  { pahari: 'asaad', gloss_en: 'summer month (June-July)', avoid: [], tags: ['time'] },
  { pahari: 'maagh', gloss_en: 'winter month (Jan-Feb)', avoid: [], tags: ['time'] },
  { pahari: 'phagun', gloss_en: 'spring month (Feb-Mar)', avoid: [], tags: ['time'] },
  { pahari: 'syau', gloss_en: 'winter / cold season', avoid: ['sardi'], tags: ['time'] },
  { pahari: 'garmi', gloss_en: 'summer / hot season', avoid: [], tags: ['time'] },
  { pahari: 'subah', gloss_en: 'morning', avoid: ['saver'], tags: ['time'] },
  { pahari: 'saajh', gloss_en: 'evening / dusk', avoid: ['shaam'], tags: ['time'] },
  { pahari: 'bhor', gloss_en: 'dawn / daybreak', avoid: [], tags: ['time'], notes: 'Poetic: "bhor ri bela" = time of dawn' },
  { pahari: 'aaj', gloss_en: 'today', avoid: [], tags: ['time'] },
  { pahari: 'kaal', gloss_en: 'tomorrow / yesterday', avoid: ['kal'], tags: ['time'], notes: 'Context determines future/past' },
  { pahari: 'parson', gloss_en: 'day after tomorrow / day before yesterday', avoid: [], tags: ['time'] },
  { pahari: 'biraan', gloss_en: 'late / delay', avoid: ['der'], tags: ['time'] },

  // ==================== EMOTIONS & STATES ====================
  { pahari: 'maya', gloss_en: 'love / affection', avoid: ['pyaar', 'mohabbat'], tags: ['emotion'] },
  { pahari: 'prem', gloss_en: 'deep love (poetic)', avoid: [], tags: ['emotion'] },
  { pahari: 'raud', gloss_en: 'anger / rage', avoid: ['gussa'], tags: ['emotion'] },
  { pahari: 'dukh', gloss_en: 'sorrow / pain', avoid: ['dard'], tags: ['emotion'] },
  { pahari: 'khushi', gloss_en: 'happiness', avoid: [], tags: ['emotion'] },
  { pahari: 'hansna', gloss_en: 'to laugh', avoid: [], tags: ['emotion'] },
  { pahari: 'rouna', gloss_en: 'to cry / weep', avoid: ['rona'], tags: ['emotion'] },
  { pahari: 'umang', gloss_en: 'enthusiasm / excitement', avoid: ['josh'], tags: ['emotion'] },
  { pahari: 'dhakka', gloss_en: 'fear / dread', avoid: ['dar'], tags: ['emotion'] },
  { pahari: 'shaunk', gloss_en: 'passion / fondness', avoid: ['shauk'], tags: ['emotion'] },
  { pahari: 'aas', gloss_en: 'hope / longing', avoid: ['umeed'], tags: ['emotion'] },
  { pahari: 'yaad', gloss_en: 'memory / remembrance', avoid: [], tags: ['emotion'] },
  { pahari: 'sapna', gloss_en: 'dream', avoid: [], tags: ['emotion'] },
  { pahari: 'chain', gloss_en: 'peace / calm', avoid: ['sukoon'], tags: ['emotion'] },
  { pahari: 'zehar', gloss_en: 'poison / something intoxicating', avoid: ['zahar'], tags: ['emotion'], notes: '"Tera hasna zehar lagda" = your smile intoxicates me' },

  // ==================== VERBS (COMMON) ====================
  { pahari: 'herda', gloss_en: 'watching / looking', avoid: ['dekhda'], tags: ['verb'] },
  { pahari: 'karna', gloss_en: 'to do', avoid: [], tags: ['verb'] },
  { pahari: 'bonna', gloss_en: 'to become / to happen', avoid: ['hona'], tags: ['verb'] },
  { pahari: 'jaana', gloss_en: 'to go', avoid: [], tags: ['verb'] },
  { pahari: 'auna', gloss_en: 'to come', avoid: ['aana'], tags: ['verb'] },
  { pahari: 'khaana', gloss_en: 'to eat', avoid: [], tags: ['verb'] },
  { pahari: 'pina', gloss_en: 'to drink', avoid: ['peena'], tags: ['verb'] },
  { pahari: 'bonna', gloss_en: 'to sow / to plant', avoid: ['bona'], tags: ['verb', 'agriculture'] },
  { pahari: 'khotna', gloss_en: 'to dig', avoid: ['khodna'], tags: ['verb'] },
  { pahari: 'kaatna', gloss_en: 'to cut', avoid: [], tags: ['verb'] },
  { pahari: 'uthna', gloss_en: 'to rise / wake up', avoid: [], tags: ['verb'] },
  { pahari: 'baitna', gloss_en: 'to sit', avoid: ['baithna'], tags: ['verb'] },
  { pahari: 'souna', gloss_en: 'to sleep', avoid: ['sona'], tags: ['verb'] },
  { pahari: 'jagna', gloss_en: 'to stay awake / be alert', avoid: [], tags: ['verb'] },
  { pahari: 'douna', gloss_en: 'to run', avoid: ['daudna'], tags: ['verb'] },
  { pahari: 'bolna', gloss_en: 'to speak / say', avoid: [], tags: ['verb'] },
  { pahari: 'gaana', gloss_en: 'to sing', avoid: ['gana'], tags: ['verb'] },
  { pahari: 'naachna', gloss_en: 'to dance', avoid: [], tags: ['verb'] },
  { pahari: 'puchhna', gloss_en: 'to ask', avoid: ['puchna'], tags: ['verb'] },
  { pahari: 'dasna', gloss_en: 'to tell', avoid: ['batana'], tags: ['verb'] },
  { pahari: 'sunna', gloss_en: 'to listen / hear', avoid: [], tags: ['verb'] },
  { pahari: 'takna', gloss_en: 'to gaze / stare', avoid: ['dekhna (stare)'], tags: ['verb'] },
  { pahari: 'kurlana', gloss_en: 'to yearn / pine for someone', avoid: ['tarsna'], tags: ['verb', 'emotion'] },
  { pahari: 'jhalakna', gloss_en: 'to shimmer / sparkle', avoid: ['chamakna'], tags: ['verb'] },
  { pahari: 'bilkhna', gloss_en: 'to sob / lament deeply', avoid: [], tags: ['verb'] },
  { pahari: 'rudna', gloss_en: 'to be stuck / entangled (emotional)', avoid: [], tags: ['verb'], notes: '"Dil rudya re" = heart is entangled' },

  // ==================== ADJECTIVES & DESCRIPTORS ====================
  { pahari: 'sheeli', gloss_en: 'cold / cool', avoid: ['thandi'], tags: ['adj'] },
  { pahari: 'tattu', gloss_en: 'hot (diminutive)', avoid: ['garam'], tags: ['adj'] },
  { pahari: 'chittu', gloss_en: 'white / bright white', avoid: ['safed'], tags: ['adj', 'beauty'] },
  { pahari: 'kaalu', gloss_en: 'black / dark', avoid: ['kala'], tags: ['adj'] },
  { pahari: 'laal', gloss_en: 'red', avoid: [], tags: ['adj'] },
  { pahari: 'pillu', gloss_en: 'yellow (diminutive)', avoid: ['peela'], tags: ['adj'] },
  { pahari: 'nilu', gloss_en: 'blue (diminutive)', avoid: ['neela'], tags: ['adj'] },
  { pahari: 'hari', gloss_en: 'green (feminine)', avoid: ['hari (acceptable)'], tags: ['adj'] },
  { pahari: 'uchcha', gloss_en: 'high / tall', avoid: ['uncha'], tags: ['adj'] },
  { pahari: 'nichcha', gloss_en: 'low / short', avoid: ['nicha'], tags: ['adj'] },
  { pahari: 'lammu', gloss_en: 'long', avoid: ['lamba'], tags: ['adj'] },
  { pahari: 'choddu', gloss_en: 'wide / broad', avoid: ['chauda'], tags: ['adj'] },
  { pahari: 'patlu', gloss_en: 'thin / slender', avoid: ['patla'], tags: ['adj', 'beauty'] },
  { pahari: 'motu', gloss_en: 'fat / thick', avoid: ['mota'], tags: ['adj'] },
  { pahari: 'badhiya', gloss_en: 'good / excellent', avoid: ['achha'], tags: ['adj'] },
  { pahari: 'bura', gloss_en: 'bad', avoid: [], tags: ['adj'] },
  { pahari: 'sunna', gloss_en: 'empty / deserted', avoid: ['suna'], tags: ['adj'] },
  { pahari: 'gahru', gloss_en: 'deep', avoid: ['gahra'], tags: ['adj'] },
  { pahari: 'chhichhora', gloss_en: 'shallow / superficial', avoid: [], tags: ['adj'] },
  { pahari: 'meetha', gloss_en: 'sweet', avoid: [], tags: ['adj'] },
  { pahari: 'khatta', gloss_en: 'sour / bitter (emotional tone)', avoid: [], tags: ['adj'] },
  { pahari: 'pyaaru', gloss_en: 'beloved / dear', avoid: ['pyaara'], tags: ['adj'] },
  { pahari: 'nyaaru', gloss_en: 'unique / separate / distinct', avoid: ['alag', 'nyara'], tags: ['adj'] },
  { pahari: 'sohna', gloss_en: 'beautiful / handsome', avoid: ['sundar'], tags: ['adj', 'beauty'] },
  { pahari: 'bholu', gloss_en: 'innocent / simple (diminutive)', avoid: ['bhola'], tags: ['adj'] },

  // ==================== CLOTHING & ADORNMENT ====================
  { pahari: 'chunnru', gloss_en: 'a red dupatta / scarf (diminutive)', avoid: ['dupatta'], tags: ['clothing'] },
  { pahari: 'jhumku', gloss_en: 'earring (diminutive)', avoid: ['bali'], tags: ['clothing'] },
  { pahari: 'dhaantu', gloss_en: 'traditional Pahari silver necklace', avoid: [], tags: ['clothing'] },
  { pahari: 'nath', gloss_en: 'nose ring', avoid: [], tags: ['clothing'] },
  { pahari: 'bindru', gloss_en: 'bindi / forehead dot (diminutive)', avoid: ['bindi'], tags: ['clothing'] },
  { pahari: 'kangan', gloss_en: 'bangles / bracelets', avoid: ['chudi'], tags: ['clothing'] },
  { pahari: 'pajeb', gloss_en: 'anklets', avoid: ['payal'], tags: ['clothing'] },
  { pahari: 'topi', gloss_en: 'traditional Pahari cap', avoid: [], tags: ['clothing'] },
  { pahari: 'saalu', gloss_en: 'woolen shawl (traditional)', avoid: ['shawl'], tags: ['clothing'] },
  { pahari: 'dhoti', gloss_en: 'traditional lower garment (men)', avoid: [], tags: ['clothing'] },
  { pahari: 'kurta', gloss_en: 'traditional upper garment', avoid: [], tags: ['clothing'] },
  { pahari: 'patka', gloss_en: 'waist sash / cummerbund', avoid: [], tags: ['clothing'] },

  // ==================== CULTURE & TRADITION ====================
  { pahari: 'mela', gloss_en: 'village fair', avoid: ['mela (acceptable)'], tags: ['culture'] },
  { pahari: 'naati', gloss_en: 'Pahari folk dance / song genre', avoid: ['bhangra'], tags: ['music'] },
  { pahari: 'jatar', gloss_en: 'village deity festival / pilgrimage', avoid: [], tags: ['culture'] },
  { pahari: 'puja', gloss_en: 'worship / prayer ritual', avoid: [], tags: ['culture'] },
  { pahari: 'devta', gloss_en: 'village deity / god', avoid: ['bhagwan'], tags: ['culture'] },
  { pahari: 'shamshan', gloss_en: 'cremation ground', avoid: [], tags: ['culture'] },
  { pahari: 'vivah', gloss_en: 'marriage / wedding', avoid: ['shaadi'], tags: ['culture'] },
  { pahari: 'byaa', gloss_en: 'wedding (colloquial)', avoid: [], tags: ['culture'] },
  { pahari: 'tith', gloss_en: 'auspicious date / festival day', avoid: ['tyohaar'], tags: ['culture'] },
  { pahari: 'bali', gloss_en: 'sacrifice (ritual offering)', avoid: [], tags: ['culture'] },
  { pahari: 'dhaam', gloss_en: 'community feast', avoid: [], tags: ['culture'] },
  { pahari: 'lukdi', gloss_en: 'torch / firebrand (festival use)', avoid: [], tags: ['culture'] },
  { pahari: 'dhol', gloss_en: 'large drum', avoid: [], tags: ['music'] },
  { pahari: 'nagada', gloss_en: 'kettle drum', avoid: [], tags: ['music'] },
  { pahari: 'shehnai', gloss_en: 'traditional wind instrument', avoid: [], tags: ['music'] },
  { pahari: 'karnal', gloss_en: 'traditional long trumpet', avoid: [], tags: ['music'] },

  // ==================== AGRICULTURE & DAILY LIFE ====================
  { pahari: 'fasal', gloss_en: 'crop / harvest', avoid: [], tags: ['agriculture'] },
  { pahari: 'gahu', gloss_en: 'wheat', avoid: ['gehu'], tags: ['agriculture'] },
  { pahari: 'makki', gloss_en: 'corn / maize', avoid: [], tags: ['agriculture'] },
  { pahari: 'jau', gloss_en: 'barley', avoid: [], tags: ['agriculture'] },
  { pahari: 'dhaan', gloss_en: 'paddy / rice plant', avoid: ['chawal'], tags: ['agriculture'] },
  { pahari: 'seb', gloss_en: 'apple', avoid: [], tags: ['agriculture'], notes: 'Iconic Himachal crop' },
  { pahari: 'bagicha', gloss_en: 'orchard', avoid: [], tags: ['agriculture'] },
  { pahari: 'hal', gloss_en: 'plough', avoid: [], tags: ['agriculture'] },
  { pahari: 'bail', gloss_en: 'ox / bullock', avoid: ['bael'], tags: ['agriculture'] },
  { pahari: 'gaai', gloss_en: 'cow', avoid: ['gaye'], tags: ['agriculture'] },
  { pahari: 'bhains', gloss_en: 'buffalo', avoid: [], tags: ['agriculture'] },
  { pahari: 'bhed', gloss_en: 'sheep', avoid: ['bhed (acceptable)'], tags: ['agriculture'] },
  { pahari: 'bakri', gloss_en: 'goat', avoid: [], tags: ['agriculture'] },
  { pahari: 'goth', gloss_en: 'cattle shed / byre', avoid: [], tags: ['agriculture'] },
  { pahari: 'chaara', gloss_en: 'fodder / animal feed', avoid: [], tags: ['agriculture'] },
  { pahari: 'ghaasni', gloss_en: 'grass cutting (task)', avoid: [], tags: ['agriculture'] },
  { pahari: 'lakdi', gloss_en: 'firewood', avoid: ['lakdi (acceptable)'], tags: ['daily life'] },
  { pahari: 'chulha', gloss_en: 'traditional stove', avoid: [], tags: ['daily life'] },
  { pahari: 'dhuwaan', gloss_en: 'smoke', avoid: ['dhuan'], tags: ['daily life'] },
  { pahari: 'paani', gloss_en: 'water', avoid: [], tags: ['daily life'] },
  { pahari: 'roti', gloss_en: 'flatbread / food (general)', avoid: [], tags: ['daily life'] },
  { pahari: 'daal', gloss_en: 'lentils', avoid: [], tags: ['daily life'] },
  { pahari: 'siddu', gloss_en: 'traditional stuffed steamed bread', avoid: [], tags: ['daily life'] },
  { pahari: 'chah', gloss_en: 'tea', avoid: ['chai'], tags: ['daily life'] },
  { pahari: 'bidi', gloss_en: 'rolled cigarette / beedi', avoid: [], tags: ['daily life'] },
  { pahari: 'hookah', gloss_en: 'water pipe (traditional smoking)', avoid: [], tags: ['daily life'] },

  // ==================== PRONOUNS ====================
  { pahari: 'main', gloss_en: 'I', avoid: [], tags: ['grammar'] },
  { pahari: 'tu', gloss_en: 'you (intimate singular)', avoid: [], tags: ['grammar'] },
  { pahari: 'tum', gloss_en: 'you (semi-formal)', avoid: [], tags: ['grammar'] },
  { pahari: 'aap', gloss_en: 'you (formal)', avoid: [], tags: ['grammar'] },
  { pahari: 'yo', gloss_en: 'this / he / she (proximate)', avoid: ['yeh'], tags: ['grammar'] },
  { pahari: 'so', gloss_en: 'that / he / she (distant)', avoid: ['woh'], tags: ['grammar'] },
  { pahari: 'ham', gloss_en: 'we', avoid: ['hum'], tags: ['grammar'] },
  { pahari: 'tumlog', gloss_en: 'you all / you people', avoid: ['tum log (acceptable)'], tags: ['grammar'] },
  { pahari: 'ye', gloss_en: 'these / they (proximate)', avoid: [], tags: ['grammar'] },
  { pahari: 'se', gloss_en: 'those / they (distant)', avoid: ['woh (plural)'], tags: ['grammar'] },

  // ==================== MISCELLANEOUS ====================
  { pahari: 'katha', gloss_en: 'talk / story / matter', avoid: ['gallan', 'baat'], tags: ['noun'] },
  { pahari: 'baat', gloss_en: 'matter / topic / conversation', avoid: [], tags: ['noun'], notes: '"Kya baat" is acceptable loan blend' },
  { pahari: 'sach', gloss_en: 'truth', avoid: [], tags: ['noun'] },
  { pahari: 'jhuth', gloss_en: 'lie / falsehood', avoid: ['jhooth'], tags: ['noun'] },
  { pahari: 'janjal', gloss_en: 'trouble / entanglement', avoid: ['museebat'], tags: ['noun'] },
  { pahari: 'takdir', gloss_en: 'fate / destiny', avoid: ['kismat'], tags: ['noun'] },
  { pahari: 'dua', gloss_en: 'blessing / prayer', avoid: [], tags: ['noun'] },
  { pahari: 'ger', gloss_en: 'to move / to wander (verb root)', avoid: ['ghum'], tags: ['verb'], notes: '"Geri na" = don\'t wander' },
  { pahari: 'pahari', gloss_en: 'of the mountains / Pahari people', avoid: [], tags: ['identity'] },
  { pahari: 'pahadan', gloss_en: 'mountain woman / Pahari woman', avoid: [], tags: ['identity'], notes: 'Feminine form' },
  { pahari: 'raja', gloss_en: 'king (in folk tales)', avoid: [], tags: ['culture'] },
  { pahari: 'rani', gloss_en: 'queen', avoid: [], tags: ['culture'] },
  { pahari: 'jadoo', gloss_en: 'magic', avoid: [], tags: ['noun'] },
  { pahari: 'nasha', gloss_en: 'intoxication', avoid: [], tags: ['emotion'], notes: 'Often metaphorical for love' },
  { pahari: 'chaska', gloss_en: 'addiction / habit (especially pleasurable)', avoid: [], tags: ['emotion'] },
];