
const LEXICON = [
  // --- BODY ---
  { pahari: 'akhi', gloss_en: 'eyes (singular / general)', avoid: ['aankhen'], tags: ['body', 'Kullui', 'Seraji'] },
  { pahari: 'akhyun', gloss_en: 'eyes (plural)', avoid: ['aankhen'], tags: ['body', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'nain', gloss_en: 'eyes (poetic)', avoid: [], tags: ['body', 'Pahari-General'], notes: 'Used in romantic/poetic contexts' },
  { pahari: 'muh', gloss_en: 'face / mouth', avoid: ['chehra'], tags: ['body', 'Kullui', 'Seraji'] },
  { pahari: 'mukharu', gloss_en: 'face (diminutive)', avoid: ['chehra', 'muh'], tags: ['body', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'gal', gloss_en: 'cheek', avoid: ['gaal'], tags: ['body', 'Kullui', 'Seraji'] },
  { pahari: 'gallu', gloss_en: 'cheek (diminutive)', avoid: ['gaal'], tags: ['body', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'dandru', gloss_en: 'teeth (diminutive -ru)', avoid: ['daant'], tags: ['body', 'Pahari-General'], notes: 'Chitte dandru = white teeth, a beauty trope' },
  { pahari: 'sir', gloss_en: 'head', avoid: ['sheeshu'], tags: ['body', 'Kullui', 'Seraji'] },
  { pahari: 'sheeshu', gloss_en: 'head', avoid: ['sir'], tags: ['body', 'Sirmauri'] },
  { pahari: 'naak', gloss_en: 'nose', avoid: [], tags: ['body', 'Pahari-General'] },
  { pahari: 'kaan', gloss_en: 'ear', avoid: [], tags: ['body', 'Pahari-General'] },
  { pahari: 'haath', gloss_en: 'hand', avoid: [], tags: ['body', 'Pahari-General'] },
  { pahari: 'pair', gloss_en: 'foot / feet', avoid: ['paon', 'per'], tags: ['body', 'Pahari-General'] },
  { pahari: 'baal', gloss_en: 'hair', avoid: [], tags: ['body', 'Pahari-General'] },

  // --- BEAUTY / ADJ ---
  { pahari: 'goru', gloss_en: 'fair / light-skinned (diminutive)', avoid: ['gora'], tags: ['beauty', 'Pahari-General'], notes: 'Fair complexion trope in folk songs' },
  { pahari: 'kaalu', gloss_en: 'dark / dusky (diminutive)', avoid: ['kala'], tags: ['beauty', 'Pahari-General'] },
  { pahari: 'sohna', gloss_en: 'beautiful / handsome', avoid: ['sundar'], tags: ['adj', 'beauty', 'Kullui', 'Seraji'] },
  { pahari: 'chittu', gloss_en: 'white / bright white', avoid: ['safed'], tags: ['adj', 'beauty', 'Pahari-General'] },
  { pahari: 'kaalu2', gloss_en: 'black / dark', avoid: ['kala'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'laal', gloss_en: 'red', avoid: [], tags: ['adj', 'Pahari-General'] },
  { pahari: 'pillu', gloss_en: 'yellow (diminutive)', avoid: ['peela'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'nilu', gloss_en: 'blue (diminutive)', avoid: ['neela'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'hari', gloss_en: 'green (feminine)', avoid: ['hari (acceptable)'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'sheeli', gloss_en: 'cold / cool', avoid: ['thandi'], tags: ['adj', 'Kullui', 'Sirmauri'] },
  { pahari: 'tattu', gloss_en: 'hot (diminutive)', avoid: ['garam'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'uchcha', gloss_en: 'high / tall', avoid: ['uncha'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'nichcha', gloss_en: 'low / short', avoid: ['nicha'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'lammu', gloss_en: 'long', avoid: ['lamba'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'choddu', gloss_en: 'wide / broad', avoid: ['chauda'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'patlu', gloss_en: 'thin / slender', avoid: ['patla'], tags: ['adj', 'beauty', 'Pahari-General'] },
  { pahari: 'motu', gloss_en: 'fat / thick', avoid: ['mota'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'badhiya', gloss_en: 'good / excellent', avoid: ['achha'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'bura', gloss_en: 'bad', avoid: [], tags: ['adj', 'Pahari-General'] },
  { pahari: 'sunna2', gloss_en: 'empty / deserted', avoid: ['suna'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'gahru', gloss_en: 'deep', avoid: ['gahra'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'chhichhora', gloss_en: 'shallow / superficial', avoid: [], tags: ['adj', 'Pahari-General'] },
  { pahari: 'meetha', gloss_en: 'sweet', avoid: [], tags: ['adj', 'Pahari-General'] },
  { pahari: 'khatta', gloss_en: 'sour / bitter (emotional tone)', avoid: [], tags: ['adj', 'Pahari-General'] },
  { pahari: 'pyaaru', gloss_en: 'beloved / dear', avoid: ['pyaara'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'nyaaru', gloss_en: 'unique / separate / distinct', avoid: ['alag', 'nyara'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'bholu', gloss_en: 'innocent / simple (diminutive)', avoid: ['bhola'], tags: ['adj', 'Pahari-General'] },
  { pahari: 'juthi', gloss_en: 'false / fake / a lie', avoid: ['jhootha'], tags: ['adj', 'Kullui', 'Seraji'], notes: 'Kullui emphasis: "Juthi bolna" = to lie' },

  // --- PEOPLE / KINSHIP ---
  { pahari: 'kudi', gloss_en: 'girl / daughter', avoid: ['larki', 'beti', 'bitti'], tags: ['people', 'Kullui', 'Seraji'] },
  { pahari: 'bitti', gloss_en: 'girl / daughter', avoid: ['larki', 'beti'], tags: ['people', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'munda', gloss_en: 'boy / son', avoid: ['larka', 'beta', 'bittu'], tags: ['people', 'Kullui', 'Seraji'] },
  { pahari: 'bittu', gloss_en: 'boy / son', avoid: ['larka', 'beta'], tags: ['people', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'baap', gloss_en: 'father', avoid: ['pita', 'papa', 'baabu'], tags: ['kinship', 'Kullui', 'Seraji'] },
  { pahari: 'baabu', gloss_en: 'father', avoid: ['pita', 'papa'], tags: ['kinship', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'amma', gloss_en: 'mother', avoid: ['mata', 'maa', 'aama'], tags: ['kinship', 'Kullui', 'Seraji'] },
  { pahari: 'aama', gloss_en: 'mother', avoid: ['mata', 'maa'], tags: ['kinship', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'bhai', gloss_en: 'brother', avoid: ['bhailu'], tags: ['kinship', 'Kullui', 'Seraji'] },
  { pahari: 'bhailu', gloss_en: 'brother', avoid: ['bhai'], tags: ['kinship', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'bhabo', gloss_en: 'brother\'s wife', avoid: ['bhabhi'], tags: ['kinship', 'Kullui', 'Seraji'] },
  { pahari: 'bhabhi', gloss_en: 'brother\'s wife', avoid: [], tags: ['kinship', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'diya', gloss_en: 'sister', avoid: ['behen', 'baani'], tags: ['kinship', 'Kullui', 'Seraji'] },
  { pahari: 'baani', gloss_en: 'sister', avoid: ['behen'], tags: ['kinship', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'babra', gloss_en: 'father\'s younger brother', avoid: ['chaachu'], tags: ['kinship', 'Kullui', 'Seraji'] },
  { pahari: 'chaachu', gloss_en: 'father\'s younger brother', avoid: [], tags: ['kinship', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'taau', gloss_en: 'father\'s elder brother', avoid: [], tags: ['kinship', 'Pahari-General'] },
  { pahari: 'mausi', gloss_en: 'mother\'s sister', avoid: [], tags: ['kinship', 'Pahari-General'] },
  { pahari: 'bua', gloss_en: 'father\'s sister', avoid: [], tags: ['kinship', 'Pahari-General'] },
  { pahari: 'dadi', gloss_en: 'paternal grandmother', avoid: [], tags: ['kinship', 'Pahari-General'] },
  { pahari: 'naani', gloss_en: 'maternal grandmother', avoid: [], tags: ['kinship', 'Pahari-General'] },
  { pahari: 'jwaai', gloss_en: 'son-in-law', avoid: [], tags: ['kinship', 'Pahari-General'] },
  { pahari: 'dulhan', gloss_en: 'bride / newlywed woman', avoid: ['bauri'], tags: ['people', 'Kullui', 'Seraji'] },
  { pahari: 'bauri', gloss_en: 'bride / newlywed woman', avoid: ['dulhan'], tags: ['people', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'dulha', gloss_en: 'groom', avoid: ['lendu'], tags: ['people', 'Kullui', 'Seraji'] },
  { pahari: 'lendu', gloss_en: 'groom', avoid: ['dulha'], tags: ['people', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'sakhi', gloss_en: 'friend (female)', avoid: ['saheli', 'saagi'], tags: ['people', 'Kullui', 'Seraji'] },
  { pahari: 'saagi', gloss_en: 'friend (female)', avoid: ['saheli'], tags: ['people', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'yaar', gloss_en: 'friend (male)', avoid: ['dost'], tags: ['people', 'Pahari-General'] },
  { pahari: 'log', gloss_en: 'people / folk', avoid: [], tags: ['people', 'Pahari-General'] },
  { pahari: 'jaat', gloss_en: 'caste / kind / type', avoid: [], tags: ['people', 'Pahari-General'] },

  // --- GRAMMAR ---
  { pahari: 'manu', gloss_en: 'to me / I, me (Kullui pronoun)', avoid: ['minjo', 'mainu', 'mujhe', 'mai', 'haan'], tags: ['grammar', 'Kullui', 'Seraji'] },
  { pahari: 'minjo', gloss_en: 'to me', avoid: ['mainu', 'mujhe'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'tenu', gloss_en: 'to you (singular)', avoid: ['tinjo', 'tujhe'], tags: ['grammar', 'Kullui', 'Seraji'] },
  { pahari: 'tinjo', gloss_en: 'to you (singular)', avoid: ['tenu', 'tujhe'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'ohnu', gloss_en: 'to him/her', avoid: ['unjo', 'use'], tags: ['grammar', 'Kullui', 'Seraji'] },
  { pahari: 'unjo', gloss_en: 'to him/her', avoid: ['ohnu', 'use'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'aapna', gloss_en: 'our / our own', avoid: ['aapdu', 'apna'], tags: ['grammar', 'Kullui', 'Seraji'], notes: 'Reflexive possessive, "aapna gaon" = our village' },
  { pahari: 'aapdu', gloss_en: 'our / our own', avoid: ['apna'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'], notes: 'Reflexive possessive, "aapdu graan" = our village' },
  { pahari: 'vich', gloss_en: 'in / inside', avoid: ['manjh', 'ch'], tags: ['grammar', 'Kullui', 'Seraji'], notes: 'Kullui uses "vich" (Kullu vich = in Kullu)' },
  { pahari: 'manjh', gloss_en: 'in / inside', avoid: ['ch', 'vich'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'], notes: 'Sirmauri/Mahasuvi uses "manjh"' },
  { pahari: 'di', gloss_en: 'genitive feminine suffix', avoid: ['ri'], tags: ['grammar', 'Kullui', 'Seraji'], notes: 'Kullui uses "di" (Kullui di boli)' },
  { pahari: 'ri', gloss_en: 'genitive feminine suffix', avoid: ['di'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'], notes: 'Sirmauri uses "ri"' },
  { pahari: 'da', gloss_en: 'genitive masculine suffix', avoid: ['ra'], tags: ['grammar', 'Kullui', 'Seraji'], notes: 'Kullui uses "da" (Munda da)' },
  { pahari: 'ra', gloss_en: 'genitive masculine suffix', avoid: ['da'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'], notes: 'Sirmauri uses "ra"' },
  { pahari: 'de', gloss_en: 'genitive oblique suffix', avoid: ['re'], tags: ['grammar', 'Kullui', 'Seraji'], notes: 'Kullui uses "de" (Log de)' },
  { pahari: 're', gloss_en: 'genitive oblique suffix', avoid: ['de'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'], notes: 'Sirmauri uses "re"' },
  { pahari: 'kidda', gloss_en: 'where', avoid: ['kahan', 'kundu', 'kuthu'], tags: ['grammar', 'Kullui', 'Seraji'] },
  { pahari: 'kuthu', gloss_en: 'where (variant)', avoid: ['kidhar', 'kidda'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'kundu', gloss_en: 'where', avoid: ['kahan'], tags: ['grammar', 'Sirmauri'] },
  { pahari: 'jado', gloss_en: 'when', avoid: ['jaalu', 'jadon', 'jab'], tags: ['grammar', 'Kullui', 'Seraji'] },
  { pahari: 'jaalu', gloss_en: 'when', avoid: ['jadon', 'jab'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'tado', gloss_en: 'then (at that time)', avoid: ['taalu', 'tadon', 'tab'], tags: ['grammar', 'Kullui', 'Seraji'] },
  { pahari: 'taalu', gloss_en: 'then (at that time)', avoid: ['tadon', 'tab'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'jo', gloss_en: 'that / which / who', avoid: ['jo (acceptable)'], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'ni', gloss_en: 'feminine marker / emphasis particle', avoid: [], tags: ['grammar', 'Pahari-General'], notes: 'As in "lai lo ni" — emphatic feminine particle' },
  { pahari: 'ta', gloss_en: 'then / so (connective)', avoid: ['to', 'phir'], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'bhi', gloss_en: 'also / too', avoid: ['vi'], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'hi', gloss_en: 'only / exactly', avoid: [], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'ho', gloss_en: 'vocative / exclamation', avoid: ['o', 'are'], tags: ['grammar', 'Pahari-General'], notes: 'Used before names: "Ho bitti..." = Oh girl...' },
  { pahari: 'ae', gloss_en: 'is (present copula)', avoid: ['hai'], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'si', gloss_en: 'was (past copula)', avoid: ['thae', 'tha'], tags: ['grammar', 'Kullui', 'Seraji'] },
  { pahari: 'thae', gloss_en: 'was (past copula)', avoid: ['tha'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'cha', gloss_en: 'is (emphatic copula)', avoid: [], tags: ['grammar', 'Pahari-General'], notes: 'Shortened from "chha"' },
  { pahari: 'kinna', gloss_en: 'how much / how many', avoid: ['kitna'], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'itna', gloss_en: 'this much', avoid: [], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'jyun', gloss_en: 'like / as / similar to', avoid: ['jaise', 'jiven'], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'tyun', gloss_en: 'like that / in that manner', avoid: ['taise', 'tiven'], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'main', gloss_en: 'I', avoid: [], tags: ['grammar', 'Pahari-General'] },

  { pahari: 'tu', gloss_en: 'you (intimate singular)', avoid: [], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'tum', gloss_en: 'you (semi-formal)', avoid: [], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'tusaan', gloss_en: 'you (formal / plural / you all)', avoid: ['aap', 'tum', 'tumlog'], tags: ['grammar', 'Kullui', 'Seraji'] },
  { pahari: 'aap', gloss_en: 'you (formal)', avoid: [], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'yo', gloss_en: 'this / he / she (proximate)', avoid: ['yeh'], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'so', gloss_en: 'that / he / she (distant)', avoid: ['woh'], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'asan', gloss_en: 'we', avoid: ['ham', 'hum'], tags: ['grammar', 'Kullui', 'Seraji'] },
  { pahari: 'ham', gloss_en: 'we', avoid: ['hum'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'] },

  { pahari: 'tumlog', gloss_en: 'you all / you people', avoid: ['tum log (acceptable)'], tags: ['grammar', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'ye', gloss_en: 'these / they (proximate)', avoid: [], tags: ['grammar', 'Pahari-General'] },
  { pahari: 'se', gloss_en: 'those / they (distant)', avoid: ['woh (plural)'], tags: ['grammar', 'Pahari-General'] },

  // --- NATURE ---
  { pahari: 'kail', gloss_en: 'blue pine tree', avoid: [], tags: ['nature', 'Kullui', 'Seraji'], notes: 'Very common in Kullu/Manali, distinct from Deodar' },
  { pahari: 'baanu', gloss_en: 'oak tree', avoid: [], tags: ['nature', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'banjar', gloss_en: 'barren / fallow land', avoid: [], tags: ['nature', 'Pahari-General'] },
  { pahari: 'bagaich', gloss_en: 'garden', avoid: ['bagh'], tags: ['nature', 'Pahari-General'] },
  { pahari: 'deodar', gloss_en: 'Himalayan cedar tree', avoid: [], tags: ['nature', 'Pahari-General'] },
  { pahari: 'pahad', gloss_en: 'mountain', avoid: ['pahad (acceptable)'], tags: ['nature', 'Pahari-General'] },
  { pahari: 'dhaar', gloss_en: 'mountain ridge / crest', avoid: [], tags: ['nature', 'Pahari-General'] },
  { pahari: 'jangle', gloss_en: 'forest', avoid: ['jungle (acceptable)'], tags: ['nature', 'Pahari-General'] },
  { pahari: 'buransh', gloss_en: 'rhododendron flower', avoid: [], tags: ['nature', 'Pahari-General'], notes: 'State flower, iconic in songs' },
  { pahari: 'khaalu', gloss_en: 'ravine / deep valley', avoid: [], tags: ['nature', 'Pahari-General'] },
  { pahari: 'gadera', gloss_en: 'mountain stream', avoid: ['nadi (small)'], tags: ['nature', 'Pahari-General'] },
  { pahari: 'naun', gloss_en: 'river (large)', avoid: ['nadi'], tags: ['nature', 'Pahari-General'] },
  { pahari: 'Beas', gloss_en: 'Beas River (lifeline of Kullu)', avoid: ['Vyas'], tags: ['nature', 'Kullui', 'Seraji'], notes: 'Referred to simply as Naun or Beas' },
  { pahari: 'chashma', gloss_en: 'spring / water source', avoid: [], tags: ['nature', 'Pahari-General'] },
  { pahari: 'ghaas', gloss_en: 'grass', avoid: [], tags: ['nature', 'Pahari-General'] },
  { pahari: 'phool', gloss_en: 'flower', avoid: [], tags: ['nature', 'Pahari-General'] },
  { pahari: 'kaante', gloss_en: 'thorns', avoid: [], tags: ['nature', 'Pahari-General'] },
  { pahari: 'badal', gloss_en: 'cloud', avoid: [], tags: ['nature', 'Pahari-General'] },
  { pahari: 'barkha', gloss_en: 'rain / monsoon', avoid: ['baarish'], tags: ['nature', 'Pahari-General'] },
  { pahari: 'baraf', gloss_en: 'snow / ice', avoid: [], tags: ['nature', 'Pahari-General'] },
  { pahari: 'dhupp', gloss_en: 'sunshine / sunlight', avoid: ['dhoop'], tags: ['nature', 'Pahari-General'] },
  { pahari: 'chaan', gloss_en: 'shade / shadow', avoid: ['chhaya'], tags: ['nature', 'Pahari-General'] },
  { pahari: 'hawa', gloss_en: 'wind / breeze', avoid: [], tags: ['nature', 'Pahari-General'] },
  { pahari: 'aakash', gloss_en: 'sky', avoid: ['asman'], tags: ['nature', 'Pahari-General'] },
  { pahari: 'taare', gloss_en: 'stars', avoid: ['sitaare'], tags: ['nature', 'Pahari-General'] },
  { pahari: 'chaand', gloss_en: 'moon', avoid: [], tags: ['nature', 'Pahari-General'] },
  { pahari: 'suuraj', gloss_en: 'sun', avoid: ['suraj'], tags: ['nature', 'Pahari-General'] },
  { pahari: 'ghughuti', gloss_en: 'a bird (songbird / dove)', avoid: ['chidiya'], tags: ['nature', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'khet', gloss_en: 'field', avoid: [], tags: ['nature', 'agriculture'] },
  { pahari: 'pashu', gloss_en: 'animal / livestock', avoid: ['janwar'], tags: ['nature', 'agriculture'] },

  // --- PLACE ---
  { pahari: 'gaon', gloss_en: 'village', avoid: ['pind', 'graan'], tags: ['place', 'Kullui', 'Seraji'] },
  { pahari: 'pind', gloss_en: 'village', avoid: ['gaon', 'graan'], tags: ['place', 'Kullui', 'Seraji'], notes: 'Influenced by Kangri/Punjabi' },
  { pahari: 'graan', gloss_en: 'village', avoid: ['pind', 'gaon'], tags: ['place', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'Kullu', gloss_en: 'Kullu (town/valley)', avoid: ['Kulu'], tags: ['place', 'Kullui', 'Seraji'] },
  { pahari: 'shahar', gloss_en: 'city / town', avoid: ['sheher'], tags: ['place', 'Pahari-General'] },
  { pahari: 'rasta', gloss_en: 'road / street', avoid: ['sadku', 'sadak'], tags: ['place', 'Kullui', 'Seraji'] },
  { pahari: 'sadku', gloss_en: 'road / street', avoid: ['sadak'], tags: ['place', 'Sirmauri', 'Mahasuvi'], notes: 'Oblique form used: "sadku pe" = on the road' },
  { pahari: 'bazaar', gloss_en: 'market', avoid: [], tags: ['place', 'Pahari-General'] },
  { pahari: 'mandir', gloss_en: 'temple', avoid: [], tags: ['place', 'Pahari-General'] },
  { pahari: 'Devta', gloss_en: 'village deity shrine / god', avoid: ['deotha', 'bhagwan'], tags: ['place', 'culture', 'Kullui', 'Seraji'], notes: 'Uppercase "Devta" is standard in Kullu culture' },
  { pahari: 'deotha', gloss_en: 'village deity shrine', avoid: [], tags: ['place', 'culture', 'Sirmauri'] },
  { pahari: 'chauraha', gloss_en: 'crossroads', avoid: [], tags: ['place', 'Pahari-General'] },
  { pahari: 'chopal', gloss_en: 'village gathering ground', avoid: [], tags: ['place', 'culture', 'Pahari-General'] },
  { pahari: 'dera', gloss_en: 'homestead / temporary dwelling', avoid: [], tags: ['place', 'Pahari-General'] },
  { pahari: 'bera', gloss_en: 'house / home', avoid: ['ghar', 'kothi'], tags: ['place', 'Kullui', 'Seraji'] },
  { pahari: 'kothi', gloss_en: 'house / mansion', avoid: ['ghar'], tags: ['place', 'Sirmauri', 'Mahasuvi'], notes: '"Aaja meri kothi" = come to my house (romantic)' },
  { pahari: 'gaushala', gloss_en: 'cowshed', avoid: [], tags: ['place', 'Pahari-General'] },
  { pahari: 'naule', gloss_en: 'stepwell / water tank', avoid: [], tags: ['place', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'shimle', gloss_en: 'Shimla (oblique case)', avoid: ['shimla'], tags: ['place', 'Sirmauri'] },
  { pahari: 'dharampur', gloss_en: 'a town / village name', avoid: [], tags: ['place', 'Sirmauri'] },
  { pahari: 'kamru', gloss_en: 'a mythological fort / place', avoid: [], tags: ['place', 'Sirmauri'] },

  // --- TIME ---
  { pahari: 'raat', gloss_en: 'night', avoid: ['rouni'], tags: ['time', 'Kullui', 'Seraji'] },
  { pahari: 'rouni', gloss_en: 'night', avoid: ['raat'], tags: ['time', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'din', gloss_en: 'day', avoid: ['dihu'], tags: ['time', 'Kullui', 'Seraji'] },
  { pahari: 'dihu', gloss_en: 'day', avoid: ['din'], tags: ['time', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'saun', gloss_en: 'monsoon month (Shravan)', avoid: ['sawan'], tags: ['time', 'Pahari-General'] },
  { pahari: 'baishakh', gloss_en: 'harvest month (April-May)', avoid: [], tags: ['time', 'Pahari-General'] },
  { pahari: 'asaad', gloss_en: 'summer month (June-July)', avoid: [], tags: ['time', 'Pahari-General'] },
  { pahari: 'maagh', gloss_en: 'winter month (Jan-Feb)', avoid: [], tags: ['time', 'Pahari-General'] },
  { pahari: 'phagun', gloss_en: 'spring month (Feb-Mar)', avoid: [], tags: ['time', 'Pahari-General'] },
  { pahari: 'sardi', gloss_en: 'winter / cold season', avoid: ['syau'], tags: ['time', 'Kullui', 'Seraji'] },
  { pahari: 'syau', gloss_en: 'winter / cold season', avoid: ['sardi'], tags: ['time', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'garmi', gloss_en: 'summer / hot season', avoid: [], tags: ['time', 'Pahari-General'] },
  { pahari: 'subah', gloss_en: 'morning', avoid: ['saver'], tags: ['time', 'Pahari-General'] },
  { pahari: 'saajh', gloss_en: 'evening / dusk', avoid: ['shaam'], tags: ['time', 'Pahari-General'] },
  { pahari: 'bhor', gloss_en: 'dawn / daybreak', avoid: [], tags: ['time', 'Pahari-General'], notes: 'Poetic: "bhor di bela" = time of dawn' },
  { pahari: 'aaj', gloss_en: 'today', avoid: [], tags: ['time', 'Pahari-General'] },
  { pahari: 'kaal', gloss_en: 'tomorrow / yesterday', avoid: ['kal'], tags: ['time', 'Kullui', 'Seraji'], notes: 'Context determines future/past' },
  { pahari: 'parson', gloss_en: 'day after tomorrow / day before yesterday', avoid: [], tags: ['time', 'Pahari-General'] },
  { pahari: 'biraan', gloss_en: 'late / delay', avoid: ['der'], tags: ['time', 'Pahari-General'] },

  // --- EMOTION ---
  { pahari: 'maya', gloss_en: 'love / affection', avoid: ['pyaar', 'mohabbat'], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'prem', gloss_en: 'deep love (poetic)', avoid: [], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'raud', gloss_en: 'anger / rage', avoid: ['gussa'], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'dukh', gloss_en: 'sorrow / pain', avoid: ['dard'], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'khushi', gloss_en: 'happiness', avoid: [], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'hansna', gloss_en: 'to laugh', avoid: [], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'rouna', gloss_en: 'to cry / weep', avoid: ['rona'], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'umang', gloss_en: 'enthusiasm / excitement', avoid: ['josh'], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'dhakka', gloss_en: 'fear / dread', avoid: ['dar'], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'shaunk', gloss_en: 'passion / fondness', avoid: ['shauk'], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'aas', gloss_en: 'hope / longing', avoid: ['umeed'], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'yaad', gloss_en: 'memory / remembrance', avoid: [], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'sapna', gloss_en: 'dream', avoid: [], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'chain', gloss_en: 'peace / calm', avoid: ['sukoon'], tags: ['emotion', 'Pahari-General'] },
  { pahari: 'zehar', gloss_en: 'poison / something intoxicating', avoid: ['zahar'], tags: ['emotion', 'Pahari-General'], notes: '"Tera hasna zehar lagda" = your smile intoxicates me' },
  { pahari: 'nasha', gloss_en: 'intoxication', avoid: [], tags: ['emotion', 'Pahari-General'], notes: 'Often metaphorical for love' },
  { pahari: 'chaska', gloss_en: 'addiction / habit (especially pleasurable)', avoid: [], tags: ['emotion', 'Pahari-General'] },

  // --- VERB ---
  { pahari: 'dekhda', gloss_en: 'watching / looking', avoid: ['herda'], tags: ['verb', 'Kullui', 'Seraji'] },
  { pahari: 'herda', gloss_en: 'watching / looking', avoid: ['dekhda'], tags: ['verb', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'karna', gloss_en: 'to do', avoid: [], tags: ['verb', 'Pahari-General'] },
  { pahari: 'hona', gloss_en: 'to become / to happen', avoid: ['bonna'], tags: ['verb', 'Kullui', 'Seraji'] },
  { pahari: 'bonna', gloss_en: 'to become / to happen', avoid: ['hona'], tags: ['verb', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'jaana', gloss_en: 'to go', avoid: [], tags: ['verb', 'Pahari-General'] },
  { pahari: 'auna', gloss_en: 'to come', avoid: ['aana'], tags: ['verb', 'Kullui', 'Sirmauri'] },
  { pahari: 'khaana', gloss_en: 'to eat', avoid: [], tags: ['verb', 'Pahari-General'] },
  { pahari: 'pina', gloss_en: 'to drink', avoid: ['peena'], tags: ['verb', 'Pahari-General'] },
  { pahari: 'khodna', gloss_en: 'to dig', avoid: ['khotna'], tags: ['verb', 'Kullui', 'Seraji'] },
  { pahari: 'khotna', gloss_en: 'to dig', avoid: ['khodna'], tags: ['verb', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'kaatna', gloss_en: 'to cut', avoid: [], tags: ['verb', 'Pahari-General'] },
  { pahari: 'uthna', gloss_en: 'to rise / wake up', avoid: [], tags: ['verb', 'Pahari-General'] },
  { pahari: 'baitna', gloss_en: 'to sit', avoid: ['baithna'], tags: ['verb', 'Pahari-General'] },
  { pahari: 'souna', gloss_en: 'to sleep', avoid: ['sona'], tags: ['verb', 'Pahari-General'] },
  { pahari: 'jagna', gloss_en: 'to stay awake / be alert', avoid: [], tags: ['verb', 'Pahari-General'] },
  { pahari: 'daudna', gloss_en: 'to run', avoid: ['douna'], tags: ['verb', 'Kullui', 'Seraji'] },
  { pahari: 'douna', gloss_en: 'to run', avoid: ['daudna'], tags: ['verb', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'bolna', gloss_en: 'to speak / say', avoid: [], tags: ['verb', 'Pahari-General'] },
  { pahari: 'gaana', gloss_en: 'to sing', avoid: ['gana'], tags: ['verb', 'Pahari-General'] },
  { pahari: 'naachna', gloss_en: 'to dance', avoid: [], tags: ['verb', 'Pahari-General'] },
  { pahari: 'puchhna', gloss_en: 'to ask', avoid: ['puchna'], tags: ['verb', 'Pahari-General'] },
  { pahari: 'dasna', gloss_en: 'to tell', avoid: ['batana'], tags: ['verb', 'Pahari-General'] },
  { pahari: 'sunna', gloss_en: 'to listen / hear', avoid: [], tags: ['verb', 'Pahari-General'] },
  { pahari: 'takna', gloss_en: 'to gaze / stare', avoid: ['dekhna (stare)'], tags: ['verb', 'Pahari-General'] },
  { pahari: 'kurlana', gloss_en: 'to yearn / pine for someone', avoid: ['tarsna'], tags: ['verb', 'emotion', 'Pahari-General'] },
  { pahari: 'jhalakna', gloss_en: 'to shimmer / sparkle', avoid: ['chamakna'], tags: ['verb', 'Pahari-General'] },
  { pahari: 'bilkhna', gloss_en: 'to sob / lament deeply', avoid: [], tags: ['verb', 'Pahari-General'] },
  { pahari: 'rulna', gloss_en: 'to be stuck / entangled (emotional)', avoid: ['rudna'], tags: ['verb', 'Kullui', 'Seraji'], notes: '"Dil rulya ae" = heart is entangled' },
  { pahari: 'rudna', gloss_en: 'to be stuck / entangled (emotional)', avoid: ['rulna'], tags: ['verb', 'Sirmauri', 'Mahasuvi'], notes: '"Dil rudya re" = heart is entangled' },
  { pahari: 'ghumna', gloss_en: 'to move / to wander', avoid: ['ger'], tags: ['verb', 'Kullui', 'Seraji'], notes: '"Gheri na" = don\'t wander' },
  { pahari: 'ger', gloss_en: 'to move / to wander (verb root)', avoid: ['ghum'], tags: ['verb', 'Sirmauri', 'Mahasuvi'], notes: '"Geri na" = don\'t wander' },

  // --- CLOTHING ---
  { pahari: 'chunni', gloss_en: 'a red dupatta / scarf', avoid: ['dupatta', 'chunnru'], tags: ['clothing', 'Kullui', 'Seraji'] },
  { pahari: 'chunnru', gloss_en: 'a red dupatta / scarf (diminutive)', avoid: ['dupatta'], tags: ['clothing', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'pullan', gloss_en: 'traditional grass/wool shoes', avoid: ['juta', 'mojri'], tags: ['clothing', 'Kullui', 'Seraji'], notes: 'Iconic Kullu/Manali footwear woven from grass' },
  { pahari: 'patu', gloss_en: 'traditional Pahari woolen shawl/wrap', avoid: ['saalu', 'shawl'], tags: ['clothing', 'Kullui', 'Seraji'] },
  { pahari: 'saalu', gloss_en: 'woolen shawl (traditional)', avoid: ['shawl'], tags: ['clothing', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'jhumku', gloss_en: 'earring (diminutive)', avoid: ['bali'], tags: ['clothing', 'Pahari-General'] },
  { pahari: 'dhaantu', gloss_en: 'traditional Pahari silver necklace', avoid: [], tags: ['clothing', 'Pahari-General'] },
  { pahari: 'nath', gloss_en: 'nose ring', avoid: [], tags: ['clothing', 'Pahari-General'] },
  { pahari: 'bindru', gloss_en: 'bindi / forehead dot (diminutive)', avoid: ['bindi'], tags: ['clothing', 'Pahari-General'] },
  { pahari: 'kangan', gloss_en: 'bangles / bracelets', avoid: ['chudi'], tags: ['clothing', 'Pahari-General'] },
  { pahari: 'pajeb', gloss_en: 'anklets', avoid: ['payal'], tags: ['clothing', 'Pahari-General'] },
  { pahari: 'topi', gloss_en: 'traditional Pahari cap', avoid: [], tags: ['clothing', 'Pahari-General'], notes: 'Kullu topi is distinctively flat and woven' },
  { pahari: 'dhoti', gloss_en: 'traditional lower garment (men)', avoid: [], tags: ['clothing', 'Pahari-General'] },
  { pahari: 'kurta', gloss_en: 'traditional upper garment', avoid: [], tags: ['clothing', 'Pahari-General'] },
  { pahari: 'patka', gloss_en: 'waist sash / cummerbund', avoid: [], tags: ['clothing', 'Pahari-General'] },

  // --- CULTURE / MUSIC ---
  { pahari: 'Dussehra', gloss_en: 'Kullu Dussehra (global fair)', avoid: ['mela (generic)'], tags: ['culture', 'Kullui', 'Seraji'], notes: 'Uppercase; unique 7-day international fair in Kullu' },
  { pahari: 'naati', gloss_en: 'Pahari folk dance / song genre', avoid: ['bhangra'], tags: ['music', 'Pahari-General'] },
  { pahari: 'mela', gloss_en: 'village fair', avoid: ['mela (acceptable)'], tags: ['culture', 'Pahari-General'] },
  { pahari: 'jatar', gloss_en: 'village deity festival / pilgrimage', avoid: [], tags: ['culture', 'Pahari-General'] },
  { pahari: 'puja', gloss_en: 'worship / prayer ritual', avoid: [], tags: ['culture', 'Pahari-General'] },
  { pahari: 'devta', gloss_en: 'village deity / god', avoid: ['bhagwan'], tags: ['culture', 'Pahari-General'] },
  { pahari: 'shamshan', gloss_en: 'cremation ground', avoid: [], tags: ['culture', 'Pahari-General'] },
  { pahari: 'vivah', gloss_en: 'marriage / wedding', avoid: ['shaadi'], tags: ['culture', 'Pahari-General'] },
  { pahari: 'byaa', gloss_en: 'wedding (colloquial)', avoid: [], tags: ['culture', 'Pahari-General'] },
  { pahari: 'tith', gloss_en: 'auspicious date / festival day', avoid: ['tyohaar'], tags: ['culture', 'Pahari-General'] },
  { pahari: 'bali', gloss_en: 'sacrifice (ritual offering)', avoid: [], tags: ['culture', 'Pahari-General'] },
  { pahari: 'dhaam', gloss_en: 'community feast', avoid: [], tags: ['culture', 'Pahari-General'] },
  { pahari: 'lukdi', gloss_en: 'torch / firebrand (festival use)', avoid: [], tags: ['culture', 'Pahari-General'] },
  { pahari: 'dhol', gloss_en: 'large drum', avoid: [], tags: ['music', 'Pahari-General'] },
  { pahari: 'nagada', gloss_en: 'kettle drum', avoid: [], tags: ['music', 'Pahari-General'] },
  { pahari: 'shehnai', gloss_en: 'traditional wind instrument', avoid: [], tags: ['music', 'Pahari-General'] },
  { pahari: 'karnal', gloss_en: 'traditional long trumpet', avoid: [], tags: ['music', 'Pahari-General'] },
  { pahari: 'raja', gloss_en: 'king (in folk tales)', avoid: [], tags: ['culture', 'Pahari-General'] },
  { pahari: 'rani', gloss_en: 'queen', avoid: [], tags: ['culture', 'Pahari-General'] },
  { pahari: 'jadoo', gloss_en: 'magic', avoid: [], tags: ['culture', 'Pahari-General'] },

  // --- AGRICULTURE ---
  { pahari: 'seb', gloss_en: 'apple', avoid: [], tags: ['agriculture', 'Kullui', 'Seraji'], notes: 'Iconic Kullu/Kinnaur crop' },
  { pahari: 'fasal', gloss_en: 'crop / harvest', avoid: [], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'gahu', gloss_en: 'wheat', avoid: ['gehu'], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'makki', gloss_en: 'corn / maize', avoid: [], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'jau', gloss_en: 'barley', avoid: [], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'dhaan', gloss_en: 'paddy / rice plant', avoid: ['chawal'], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'bagicha', gloss_en: 'orchard', avoid: [], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'hal', gloss_en: 'plough', avoid: [], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'bail', gloss_en: 'ox / bullock', avoid: ['bael'], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'gaai', gloss_en: 'cow', avoid: ['gaye'], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'bhains', gloss_en: 'buffalo', avoid: [], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'bhed', gloss_en: 'sheep', avoid: ['bhed (acceptable)'], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'bakri', gloss_en: 'goat', avoid: [], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'goth', gloss_en: 'cattle shed / byre', avoid: [], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'chaara', gloss_en: 'fodder / animal feed', avoid: [], tags: ['agriculture', 'Pahari-General'] },
  { pahari: 'ghaasni', gloss_en: 'grass cutting (task)', avoid: [], tags: ['agriculture', 'Pahari-General'] },

  // --- DAILY LIFE ---
  { pahari: 'daana', gloss_en: 'food / meal / grain', avoid: ['khana'], tags: ['daily life', 'Kullui', 'Seraji'], notes: '"Daana khana" is frowned upon, just use "Daana"' },
  { pahari: 'lakdi', gloss_en: 'firewood', avoid: ['lakdi (acceptable)'], tags: ['daily life', 'Pahari-General'] },
  { pahari: 'chulha', gloss_en: 'traditional stove', avoid: [], tags: ['daily life', 'Pahari-General'] },
  { pahari: 'dhuwaan', gloss_en: 'smoke', avoid: ['dhuan'], tags: ['daily life', 'Pahari-General'] },
  { pahari: 'paani', gloss_en: 'water', avoid: [], tags: ['daily life', 'Pahari-General'] },
  { pahari: 'roti', gloss_en: 'flatbread / food (general)', avoid: [], tags: ['daily life', 'Pahari-General'] },
  { pahari: 'daal', gloss_en: 'lentils', avoid: [], tags: ['daily life', 'Pahari-General'] },
  { pahari: 'siddu', gloss_en: 'traditional stuffed steamed bread', avoid: [], tags: ['daily life', 'Pahari-General'] },
  { pahari: 'chah', gloss_en: 'tea', avoid: ['chai'], tags: ['daily life', 'Pahari-General'] },
  { pahari: 'bidi', gloss_en: 'rolled cigarette / beedi', avoid: [], tags: ['daily life', 'Pahari-General'] },
  { pahari: 'hookah', gloss_en: 'water pipe (traditional smoking)', avoid: [], tags: ['daily life', 'Pahari-General'] },

  // --- NOUN / MISC ---
  { pahari: 'katha', gloss_en: 'talk / story / matter', avoid: ['gallan', 'baat'], tags: ['noun', 'Sirmauri', 'Mahasuvi'] },
  { pahari: 'baat', gloss_en: 'matter / topic / conversation', avoid: [], tags: ['noun', 'Kullui', 'Seraji'], notes: '"Kya baat" is acceptable loan blend' },
  { pahari: 'gal', gloss_en: 'talk / matter', avoid: ['baat'], tags: ['noun', 'Kullui', 'Seraji'], notes: '"Ki gal ae?" = What is the matter?' },
  { pahari: 'sach', gloss_en: 'truth', avoid: [], tags: ['noun', 'Pahari-General'] },
  { pahari: 'jhuth', gloss_en: 'lie / falsehood', avoid: ['jhooth'], tags: ['noun', 'Pahari-General'] },
  { pahari: 'janjal', gloss_en: 'trouble / entanglement', avoid: ['museebat'], tags: ['noun', 'Pahari-General'] },
  { pahari: 'takdir', gloss_en: 'fate / destiny', avoid: ['kismat'], tags: ['noun', 'Pahari-General'] },
  { pahari: 'dua', gloss_en: 'blessing / prayer', avoid: [], tags: ['noun', 'Pahari-General'] },
  { pahari: 'pahari', gloss_en: 'of the mountains / Pahari people', avoid: [], tags: ['identity', 'Pahari-General'] },
  { pahari: 'pahadan', gloss_en: 'mountain woman / Pahari woman', avoid: [], tags: ['identity', 'Pahari-General'], notes: 'Feminine form' },

  // --- SERAJI-SPECIFIC: Banjar Valley / Jibhi dialect ---
  { pahari: 'hyūn', gloss_en: 'yesterday (Seraji archaic form)', avoid: ['kāl', 'kal'], tags: ['time', 'Seraji'], notes: 'Seraji retains archaic form; standard Kullui uses "kāl"' },
  { pahari: 'byāl', gloss_en: 'yesterday (alternative Seraji)', avoid: [], tags: ['time', 'Seraji'], notes: 'Archaic retention alongside "hyūn"' },
  { pahari: 'parhyūn', gloss_en: 'day before yesterday (Seraji)', avoid: [], tags: ['time', 'Seraji'] },
  { pahari: 'bhyāg', gloss_en: 'tomorrow (Seraji archaic form)', avoid: ['bhāg'], tags: ['time', 'Seraji'], notes: 'Seraji retains older aspirated form; standard Kullui uses "bhāg"' },
  { pahari: 'parbhyāg', gloss_en: 'day after tomorrow (Seraji)', avoid: [], tags: ['time', 'Seraji'] },
  { pahari: 'rāta', gloss_en: 'night (Seraji, with terminal vowel)', avoid: [], tags: ['time', 'Seraji'], notes: 'Seraji often retains terminal vowel where Kullui drops it: "rāta" vs "rāt"' },
  { pahari: 'sveryā', gloss_en: 'morning (Seraji, soft y palatalization)', avoid: [], tags: ['time', 'Seraji'], notes: 'Distinctive Seraji pronunciation with soft palatalized "y"' },
  { pahari: 'sanjhā', gloss_en: 'evening (Seraji variant)', avoid: [], tags: ['time', 'Seraji'] },
  { pahari: 'bhyākhal', gloss_en: 'evening / dusk (Seraji)', avoid: [], tags: ['time', 'Seraji'], notes: 'Archaic Seraji form for evening' },
  { pahari: 'gār', gloss_en: 'river / mountain stream (Seraji)', avoid: [], tags: ['nature', 'Seraji'], notes: 'Shorter form vs standard Kullui "gārā"; common in Banjar/Tirthan region' },
  { pahari: 'gad', gloss_en: 'mountain stream / rivulet (Seraji)', avoid: [], tags: ['nature', 'Seraji'], notes: 'Used for smaller streams feeding the Tirthan River' },
  { pahari: 'thāch', gloss_en: 'high-altitude meadow (Seraji)', avoid: [], tags: ['nature', 'Seraji'], notes: 'Distinctive Seraj landscape term; alpine pastures above Jibhi' },
  { pahari: 'ragh', gloss_en: 'mountain slope / pasture (Seraji)', avoid: [], tags: ['nature', 'Seraji'], notes: '"Ragha" = on the slope — common in Seraj geography' },
  { pahari: 'sar', gloss_en: 'high-altitude lake (Seraji)', avoid: [], tags: ['nature', 'Seraji'], notes: 'Used for glacial lakes near Jalori Pass' },
  { pahari: 'dhār', gloss_en: 'mountain ridge (Seraji pronunciation)', avoid: [], tags: ['nature', 'Seraji'], notes: 'Seraji retains heavy retroflex "ḍh" sound' },
  { pahari: 'kāṭh', gloss_en: 'wood / timber (Seraji)', avoid: [], tags: ['daily life', 'Seraji'], notes: 'Referenced in Kath-Kuni architecture; "kāṭh" = deodar timber' },
  { pahari: 'chān', gloss_en: 'wooden balcony / veranda (Seraji)', avoid: [], tags: ['architecture', 'Seraji'], notes: 'Kath-Kuni house feature; carved wooden balcony with geometric patterns' },
  { pahari: 'ubār', gloss_en: 'courtyard (Seraji)', avoid: [], tags: ['architecture', 'Seraji'], notes: 'Central courtyard of traditional Seraj homes' },
  { pahari: 'dhāj', gloss_en: 'dry stone wall (Seraji)', avoid: [], tags: ['architecture', 'Seraji'], notes: 'Dry stone masonry terracing Banjar Valley slopes' },
  { pahari: 'gharāt', gloss_en: 'watermill / gharat (Seraji)', avoid: [], tags: ['daily life', 'Seraji'], notes: 'Traditional water-powered grain mill along Tirthan streams' },
  { pahari: 'khyet', gloss_en: 'field (Seraji, palatalized)', avoid: [], tags: ['nature', 'Seraji'], notes: 'Slight palatalization distinguishes Seraji "khyet" from general "khet"' },
  { pahari: 'bāri', gloss_en: 'orchard / garden (Seraji)', avoid: [], tags: ['nature', 'Seraji'], notes: 'Apple orchards of Banjar Valley' },
  { pahari: 'deyor', gloss_en: 'god / village deity (Seraji)', avoid: [], tags: ['culture', 'Seraji'], notes: 'Shringa Rishi devta is the primary deyor of Banjar' },
  { pahari: 'dev', gloss_en: 'deity / divine (Seraji, ritual)', avoid: [], tags: ['culture', 'Seraji'], notes: 'Used in formal/devotional contexts' },
  { pahari: 'ghara', gloss_en: 'house / home (Seraji alt.)', avoid: [], tags: ['place', 'Seraji'], notes: 'Alternative to "kud" / "bera"; older speakers in Jibhi use "ghara"' },
  { pahari: 'Jibhi', gloss_en: 'Jibhi (Jihbi) — Banjar Valley village', avoid: [], tags: ['place', 'Seraji'], notes: 'Primary village in the Banjar Valley, Tirthan River' },
  { pahari: 'Tirthan', gloss_en: 'Tirthan River (Seraj valley lifeline)', avoid: [], tags: ['nature', 'Seraji'], notes: 'Trout-fishing stream; tributary of Beas' },
  { pahari: 'Banjar', gloss_en: 'Banjar Valley / Banjar (town)', avoid: [], tags: ['place', 'Seraji'], notes: 'Administrative region of Seraj; Banjar Mela' },
  { pahari: 'Jalori', gloss_en: 'Jalori Pass (Seraj high pass)', avoid: [], tags: ['place', 'Seraji'], notes: 'Historical trade route connecting Kullu to Shimla' },
  { pahari: 'Seraj', gloss_en: 'Seraj / Seraji region (Banjar Valley area)', avoid: [], tags: ['place', 'Seraji'] },
  { pahari: 'Shringa', gloss_en: 'Shringa Rishi (patron deity of Banjar)', avoid: [], tags: ['culture', 'Seraji'], notes: 'Shringa Rishi Temple in Banjar — primary devta of Seraj' },
  { pahari: 'Shikari', gloss_en: 'Mata Shikari Devi (goddess)', avoid: [], tags: ['culture', 'Seraji'], notes: 'Hilltop temple near Janjehli; Seraj deity' },
];
export default LEXICON;
